# \u9879\u76EE\u7AEF\u53E3
server:
  port: 9081

# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: homework

  datasource:
    username: david
    password: abcd.1234
    url: jdbc:sqlite:commnets.db
    driver-class-name: org.sqlite.JDBC
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true


